name: Haxe-Rename

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ['4.3.6', 'nightly']
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set Git Auto CRLF to false on Windows
      if: matrix.platform == 'windows-latest'
      run: git config --global core.autocrlf false
    - name: Checkout Formatter sources
      uses: actions/checkout@v1
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Run npm install
      run: npm ci
    - name: Install Haxe version ${{ matrix.haxe-version }}
      run: |
        npx lix download haxe ${{ matrix.haxe-version }}
        npx lix use haxe ${{ matrix.haxe-version }}
    - name: Run lix download
      run: npx lix download
    - name: Print versions
      run: |
        npx haxe -version
        npx neko -version
        npx haxelib list
    - name: Build Nodejs version
      run: npx haxe build.hxml
    - name: Run Nodejs tests
      run: npx haxe -D codecov_json test.hxml
    - name: Coverage report
      if: success() && matrix.platform == 'ubuntu-latest' && matrix.haxe-version != 'nightly'
      uses: livewing/lcov-job-summary@v1.1.0
      with:
        lcov: lcov.info
